const subCatLookup = {
    "gym-machines-attachments": "Gym Machines & Attachments",
    "landmine-handles": "Landmine Posts & Handles",
    "parallel-bars": "Parallel Bars",
    "power-cages-racks": "Power Cages & Racks",
    "power-rack-attachments": "Power Rack Attachments",
    "pull-up-bars": "Pull Up Bars",
    "situp-benches": "Sit Up Benches & Bars",
    "squat-racks-stands": "Squat Racks & Stands",
    "weight-benches": "Weight Benches",
    "weightlifting-equipment": "Weightlifting Equipment",
    "bars": "Bars",
    "bumper-plates": "Bumper Plates",
    "dumbbells": "Dumbbells",
    "kettlebells": "Kettlebells",
    "medicine-balls": "Medicine Balls",
    "sandbags": "Sandbags",
    "slam-balls": "Slam Balls",
    "weight-plates": "Weight Plates",
    "weight-sets-kits": "Weight Sets & Kits",
    "wearable-weights": "Wearable Weights",
    "battle-ropes": "Battle Ropes",
    "boxing-equipment": "Boxing Equipment",
    "cardio-equipment": "Cardio Equipment",
    "core-sliders": "Core Sliders",
    "exercise-mats": "Exercise Mats",
    "exercise-steps": "Exercise Steps",
    "hula-hoops": "Hula Hoops",
    "pilates-yoga": "Pilates & Yoga",
    "plyo-jump-boxes": "Plyo Jump Boxes",
    "push-up-handles": "Push Up Handles",
    "resistance-bands": "Resistance Bands",
    "rollers": "Rollers",
    "skipping-ropes": "Skipping Ropes",
    "bar-storage": "Bar Storage",
    "dumbbell-storage": "Dumbell Storage",
    "freestanding-gym-storage": "Freestanding Gym Storage",
    "kettlebell-storage": "Kettlebell Storage",
    "plate-storage": "Plate Storage",
    "rack-mounted-storage": "Rack Mounted Storage",
    "wall-mounted-storage": "Wall Mounted Storage",
    "barbell-pads": "Barbell Pads",
    "clothing-apparel": "Clothing & Apparel",
    "gift-vouchers": "Gift Vouchers",
    "grip-training": "Grip Training",
    "gym-flags": "Gym Floor Mats",
    "gym-floor-mats": "Gym Flags",
    "gym-interval-timers": "Gym Interval Timers",
    "straps-wraps-sleeves": "Lifting Straps, Wraps & Sleeves",
    "merchandise": "Merchandise",
    "spares-replacements": "Spares & Replacements",
    "tools": "Tools",
    "weightlifting-belts": "Weightlifting Belts"
}

export default subCatLookup